-- ProductRepository_findAllProductActive => hiển thị product lên index
SELECT *
	, CATEGORY.CATEGORY_NAME
	, ORIGIN.ORIGIN_NAME
	, PRODUCT_IMG2D.PRODUCT_IMG
	, PRODUCT_PRICE.PRODUCT_PRICE
	, WAREHOUSE.PRODUCT_QUANTITY AS IMP_QUANTITY
FROM PRODUCT PR
	LEFT JOIN CATEGORY 
		ON PR.CATEGORY = CATEGORY.CATEGORY_ID
	LEFT JOIN ORIGIN 
		ON PR.ORIGIN = ORIGIN.ORIGIN_ID
	LEFT JOIN PRODUCT_IMG2D
		ON PR.PRODUCT_ID = PRODUCT_IMG2D.ID_PRODUCT_IMG2D
	LEFT JOIN PRODUCT_PRICE
		ON PR.PRODUCT_ID = PRODUCT_PRICE.PRODUCT_PRICE_ID
	LEFT JOIN warehouse 
		ON PR.PRODUCT_ID = warehouse.product
WHERE PR.PRODUCT_DISABLE = 0
ORDER BY PRODUCT_ID
OFFSET  /*offset*/ ROWS FETCH NEXT  /*sizeOfPage*/ ROWS ONLY